### ISSUE TITLE
Web-based Control Panel

### ISSUE THREAD

**Issue by magroader** [lilserf/bot-on-the-clocktower#16]
I don't know how easy this is, but some bots have a web-based control panel that can be used to poke at a bot, rather than needing to send messages to a channel.  This would be a super cool API, and something you could pop out to another window and use buttons to (for example) switch to night and day.

**Comment by lilserf** [comment]
I'm guessing this is just done by having a separate web application that's hitting the same URLs - the python bot is really hitting GET/POST apis at Discord to do everything anyway, so you could make a web app that does the same.

All this to say that it's not super straightforward :D

**Comment by magroader** [comment]
That actually made it sound easier to me. Assuming you can figure out what those get/posts are, a simple website that can hit those sounds pretty straightforward. Of course, you'd need some way to identify which server you are.

I'm picturing something like sending the bot the command "!web" and it returns a link to a site that already knows what your server is and what commands to send.

**Comment by lilserf** [comment]
Figuring out what the python api is doing behind the scenes and reimplementing literally all the python logic in JS to do all those things, including managing rate limits and other stuff that’s abstracted away, doesn’t sound very easy to me 😁
For server choice there’s probably something possible by authenticating with discord itself

**Comment by magroader** [comment]
Oh no, that's not what I meant at all.

I meant a website to talk to the BOT, which in turn talks to Discord. I didn't mean reimplementing the entire Bot in JavaScript.

Other Bots definitely have configuration sites in some way that interact with their bots. Perhaps they just poke at a DB which the bot uses, I'm not sure.

**Comment by lilserf** [comment]
Yeah I’m not sure how that would be accomplished 🤔

**Comment by magroader** [comment]
Now that we have nice buttons in Discord, I don't think this is useful anymore
