### ISSUE TITLE
bot is offline - cannot start a game or complete any commands

### ISSUE THREAD

**Issue by zoebeth** [lilserf/bot-on-the-clocktower#163]
the bot has been offline for a while now. i'm not sure if there is a reason for this, can someone please clarify?

**Comment by lilserf** [comment]
Oh no! The reason is that I have not personally used it lately, and did not realize it was off-line. I am not able to get to a PC right now unfortunately

**Comment by zoebeth** [comment]
Thank you for letting me know! Not a problem, we will use moveer until your bot is back online. I was just worried it was something I'd done! Great work, btw.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by lilserf** [comment]
I've restarted the bot! No idea what happened, the process was still running but apparently it was just busted :(
Thanks for the heads-up.
