### ISSUE TITLE
Encountering timeout error since update

### ISSUE THREAD

**Issue by StrawdogG2** [lilserf/bot-on-the-clocktower#164]
Bot on the Clocktown has been encountering an error, despite it working for me a few days ago. I tried removing and reinviting the bot but the issue persists. Using /createtown, it makes all the channels and roles before saying "An error occurred processing this command - please check your private messages for a detailed report."

This is the error message I got simply for /towninfo:

Interaction error [Guild: 974101255796457482]
Exception: TimeoutException
Message:   `A timeout occurred after 30000ms selecting a server using CompositeServerSelector{ Selectors = ReadPreferenceServerSelector{ ReadPreference = { Mode : Primary } }, LatencyLimitingServerSelector{ AllowedLatencyRange = 00:00:00.0150000 }, OperationsCountServerSelector }. Client view of cluster state is { ClusterId : "1", ConnectionMode : "ReplicaSet", Type : "ReplicaSet", State : "Connected", Servers : [{ ServerId: "{ ClusterId : 1, EndPoint : "Unspecified/cluster0-shard-00-00.eylae.mongodb.net:27017" }", EndPoint: "Unspecified/cluster0-shard-00-00.eylae.mongodb.net:27017", ReasonChanged: "Heartbeat", State: "Connected", ServerVersion: , TopologyVersion: { "processId" : ObjectId("649318caac5146882b267da7"), "counter" : NumberLong(5) }, Type: "ReplicaSetSecondary", Tags: "{ nodeType : ELECTABLE, provider : AWS, workloadType : OPERATIONAL, region : US_EAST_1 }", WireVersionRange: "[0, 17]", LastHeartbeatTimestamp: "2023-06-22T20:27:55.3462632Z", LastUpdateTimestamp: "2023-06-22T20:27:55.3462637Z" }, { ServerId: "{ ClusterId : 1, EndPoint : "Unspecified/cluster0-shard-00-01.eylae.mongodb.net:27017" }", EndPoint: "Unspecified/cluster0-shard-00-01.eylae.mongodb.net:27017", ReasonChanged: "ReportedPrimaryIsStale", State: "Disconnected", ServerVersion: , TopologyVersion: , Type: "Unknown", LastHeartbeatTimestamp: null, LastUpdateTimestamp: "2023-06-22T20:27:55.0542450Z" }, { ServerId: "{ ClusterId : 1, EndPoint : "Unspecified/cluster0-shard-00-02.eylae.mongodb.net:27017" }", EndPoint: "Unspecified/cluster0-shard-00-02.eylae.mongodb.net:27017", ReasonChanged: "Heartbeat", State: "Connected", ServerVersion: , TopologyVersion: { "processId" : ObjectId("6493d8fb251af2de6c6eb0b3"), "counter" : NumberLong(4) },

Thanks!

**Comment by magroader** [comment]
This is happening for me too - it appears to be a connection issue connecting to MongoDB (which stores info about the towns).

**Comment by lilserf** [comment]
Why do these things always happen when I'm out of town on vacation? 😕

**Comment by magroader** [comment]
@lilserf I tried running the dev version of the bot and `/towninfo` worked fine there. The main bot appears to be timing out when talking to MongoDB.

I'm wondering if maybe it just needs to be restarted, so I'm going to try to get it up-to-date with `main` (which just has a test in it) so it restarts.

**Comment by lilserf** [comment]
Your empty commit did not cause a restart, unfortunately. I've restarted the bot now and I think it's working correctly.
Sorry for the timing of this happening while I was unable to act on it, but it should be fixed now.
