### ISSUE TITLE
Consider a DEV mongo db or cluster

### ISSUE THREAD

**Issue by lilserf** [lilserf/bot-on-the-clocktower#30]
We might not want our local-running bots to touch the "prod" mongo cluster/db

**Comment by lilserf** [comment]
We have a dev Collection at least, but its on the same cluster

**Comment by magroader** [comment]
What is the benefit? Not sure what independent clusters helps with

**Comment by lilserf** [comment]
It's just probably safer if us messing around with new dev features doesn't have the potential to screw up the Prod data

**Comment by magroader** [comment]
@lilserf I think this is done, no?

**Comment by lilserf** [comment]
Yup!
