### ISSUE TITLE
No need of else statement

### ISSUE THREAD

**Issue by AliHaider20** [lilserf/bot-on-the-clocktower#53]
class botcBot -> function getTownInfo. There's no need to else statement there.

Explanation:
If the IF statement returns True it will return TownInfo(ctx.guild, doc) and jumps out of the function else the interpreter will go to the next line and then it will return None and jump out of the function.

**Comment by magroader** [comment]
Existing code:
```
        if doc:
            return TownInfo(ctx.guild, doc)
        else:
            return None
```

Suggestion:
```
        if doc:
            return TownInfo(ctx.guild, doc)
        return None
```

For that matter, the code could be:
```
        return doc and TownInfo(ctx.guild, doc) or None
```

**Comment by magroader** [comment]
As mentioned in #54 , you are welcome to submit Pull Requests to help clean up the code, no overhead of making a new Issue required! If you put "Fixes #issuenum" in your Pull Request description, it'll auto-link them.

I believe the name of this shorthand is called "ShortHand Ternary" (https://book.pythontips.com/en/latest/ternary_operators.html)

**Comment by AliHaider20** [comment]
Thanks a lot. Can you also explain how to add labels i.e tags to issues. I googled it much but can't understand. I'm not getting any option on RHS when I open any issue.

**Comment by magroader** [comment]
Ah, yeah I know that feeling, I've hit that before as well. Labels can only be added by people with certain permissions in the project repository, so only lilserf and I can do it.

If you'd like to contribute to Bot on the Clocktower or have questions, please make a change and submit a Pull Request or toss me an email (link in my profile). If you find any functionality bugs or have feature requests, please continue to submit issues! I'll close this one though as it's just a style suggestion that could be done via Pull Request.
