### ISSUE TITLE
!destroytown Not destroying some number of cottages as well as the Graveyard

### ISSUE THREAD

**Issue by magroader** [lilserf/bot-on-the-clocktower#56]
Doing:
```
!createtown TestTown
```
Followed pretty immediately by:
```
!destroytown TestTown
```

Appears to fail to destroy some stuff. Message:
> I destroyed what I knew about for Town TestTown2.
> 
> I did not destroy some things I was unfamiliar with:
>  * TestTown2 - Night / Cottage (channel)
>  * TestTown2 / Graveyard (channel)
>
> You can destroy them and run this command again.
>
> I did not destroy these things yet, just in case you still need them:
>  * TestTown2 - Night (category)
>  * TestTown2 / botc_mover (channel)
>  * TestTown2 (category)
>  * TestTown2 Villager (role)
>  * TestTown2 Storyteller (role)

However, as far as I can tell, the Cottage and the Graveyard DID get destroyed. So there appears to be a bug where it thinks it didn't destroy the Graveyard, or something. Might be a lag issue of some kind, may need to tweak how we determine whether a channel was destroyed.

Running it again works fine.

**Comment by lilserf** [comment]
My only thought is that something is getting queued up or cached in the discord.py internals. We await for the channels to be deleted, then _immediately_ check the channel list and flag anything in there.
From what I've seen, the stuff _is_ actually deleted despite the bot not thinking it was.

We could just remember the channels we've called `delete` on, and not warn on those, as long as we're pretty sure those deletes will eventually go through.

**Comment by lilserf** [comment]
This is a python-specific bug; will reopen in the future if C# has similar issues
