### ISSUE TITLE
Add optional timer to !day -> !vote

### ISSUE THREAD

**Issue by lilserf** [lilserf/bot-on-the-clocktower#61]
- Add a way that you can specify a number of minutes when you start the !day phase
- After N-1 minutes the bot will post a 1-minute warning to the players (or to the text chat if we add knowledge of the text chat)
- After N minutes the bot will auto-run the !vote command

**Comment by magroader** [comment]
I think I'd want:
* ability to do this independently of !day if desired
* ability to auto run !vote or not
The main feature is the timer and warning message
