### ISSUE TITLE
Refactor calls to discord.py away to interfaces

### ISSUE THREAD

**Issue by magroader** [lilserf/bot-on-the-clocktower#69]
We have lots of calls to discord.py

discord.py MAY be going away, so we should distance our business logic from it

Start with moving logic out to its own file
End with any calls to discord.py stuff from business logic being through an interface we can swap out later

**Comment by lilserf** [comment]
In feature/69_abstract_gameplay I have parts of the GameplayCog moved out to a GameplayImpl file.
I intend this class to only contain the night/day/vote/currgame/endgame/setstorytellers functionality
I plan for a separate messaging class to handle the !evil command and its related stuff
