### ISSUE TITLE
Store (anonymized) usage statistics

### ISSUE THREAD

**Issue by lilserf** [lilserf/bot-on-the-clocktower#81]
How many games are being played in a week / day / whatever?
How many different guilds involved?
How many players in a game?
How long do the games last? (Hard to deduce)

Don't store or share any user or guild-specific information... guild IDs okay?

**Comment by magroader** [comment]
How long they last isn't all that hard to deduce - we know when they start, and we know when they end or have been idle for X hours. When idling out, that means we don't know how long the LAST day is, but we could guess 10 minutes or something.

**Comment by magroader** [comment]
Oh good point, I was thinking "a game" meant like "a night of games" not a singular game. But you're right

**Comment by lilserf** [comment]
New C# bot does this
